services:
  - type: web
    name: shmool-server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_HOST
        value: aws-0-ap-northeast-1.pooler.supabase.com
      - key: SUPABASE_PORT
        value: "6543"
      - key: SUPABASE_DB
        value: postgres
      - key: SUPABASE_USER
        value: postgres.gpzjrwvgeivdcqnyzgxk
      - key: SUPABASE_PASS
        sync: false
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        sync: false
